/** Adversarial and edge-case prompts for chat security tests (Phase 8). */
export const ADVERSARIAL_CHAT_PROMPTS: Array<{
  id: string;
  input: string;
  expectReject?: boolean;
}> = [
  { id: "liq-1", input: "{% assign x = 1 %}", expectReject: true },
  { id: "liq-2", input: "{{ product.title }}", expectReject: true },
  { id: "liq-3", input: "Change headline to {{ shop.name }}", expectReject: true },
  { id: "liq-4", input: "{% render 'malicious' %}", expectReject: true },
  { id: "liq-5", input: "Add section {% if true %}", expectReject: true },
  { id: "path-1", input: "../../../etc/passwd", expectReject: true },
  { id: "path-2", input: "sections/evil.liquid", expectReject: true },
  { id: "path-3", input: "templates/index.liquid", expectReject: true },
  { id: "path-4", input: "snippets/inject.liquid", expectReject: true },
  { id: "path-5", input: "layout/theme.liquid", expectReject: true },
  { id: "html-1", input: "<script>alert(1)</script>", expectReject: true },
  { id: "html-2", input: "<img src=x onerror=alert(1)>", expectReject: true },
  { id: "html-3", input: "javascript:alert(1)", expectReject: true },
  { id: "html-4", input: "<div onclick=steal()>click</div>", expectReject: true },
  { id: "html-5", input: "Change color to <b>red</b>", expectReject: true },
  { id: "safe-1", input: "Change colors to black" },
  { id: "safe-2", input: "Add FAQ section" },
  { id: "safe-3", input: "Make hero smaller" },
  { id: "safe-4", input: "Change the headline to Summer Sale" },
  { id: "safe-5", input: "Add trust badges" },
  { id: "safe-6", input: "Change colors to #1a1a1a" },
  { id: "safe-7", input: "Add a rich text section" },
  { id: "safe-8", input: "Set headline to Free shipping today" },
  { id: "edge-1", input: "   " , expectReject: true },
  { id: "edge-2", input: "a".repeat(2001), expectReject: true },
  { id: "mix-1", input: "Change colors to black and add FAQ" },
  { id: "mix-2", input: "Make hero smaller please" },
  { id: "noop-1", input: "Hello there" },
  { id: "noop-2", input: "What can you do?" },
  { id: "liq-6", input: "Use liquid {% endfor %}", expectReject: true },
  { id: "liq-7", input: "Output }} broken", expectReject: true },
  { id: "path-6", input: "read ../config/settings_data.json", expectReject: true },
  { id: "path-7", input: "sections/../secrets", expectReject: true },
  { id: "html-6", input: "<iframe src=evil.com>", expectReject: true },
  { id: "html-7", input: "onload=alert(1)", expectReject: true },
  { id: "safe-9", input: "Change color to gold" },
  { id: "safe-10", input: "Add video section" },
  { id: "safe-11", input: "Hide the hero" },
  { id: "safe-12", input: "Insert an image banner section" },
  { id: "liq-8", input: "{{ 'x' | asset_url }}", expectReject: true },
  { id: "liq-9", input: "{% comment %}x{% endcomment %}", expectReject: true },
  { id: "path-8", input: "templates/customers/account.liquid", expectReject: true },
  { id: "path-9", input: "assets/malware.js", expectReject: false },
  { id: "html-8", input: "<svg onload=1>", expectReject: true },
  { id: "html-9", input: "data:text/html,<script>", expectReject: true },
  { id: "safe-13", input: "Change the headline to Move Better" },
  { id: "safe-14", input: "Add featured collection" },
  { id: "safe-15", input: "Make the hero smaller" },
  { id: "liq-10", input: "Include {% include 'bad' %}", expectReject: true },
  { id: "noop-3", input: "Thanks!" },
  { id: "noop-4", input: "Looks good" },
  { id: "safe-16", input: "Change colors to blue" },
  { id: "safe-17", input: "Add faq section" },
  { id: "safe-18", input: "Add FAQ" },
  { id: "path-10", input: "open sections/header.liquid", expectReject: true },
];
