# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b760488893fede55f5a36aadef5de8c"
name = "MVP"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_themes,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]
